=== a42ss/flex-cli/src/lcli/config/samples/prototypes/commands.xsd
<?xml version="1.0" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="commands" type="commandList"/>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="uniqueBlockId">
            <xs:annotation>
                <xs:documentation>
                    Unique command id
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="command"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="commandList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="command" type="command"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="command">
        <xs:sequence>
            <xs:element name="type"/>
            <xs:element name="description"/>
            <xs:element name="args" minOccurs="0" type="argsType"/>
            <xs:element name="commands" minOccurs="0" type="commandList"/>
        </xs:sequence>
        <xs:attributeGroup ref="commandAttributeGroup"/>
    </xs:complexType>

    <xs:attributeGroup name="commandAttributeGroup">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="argsType">
        <xs:sequence>
            <xs:element minOccurs="0" name="wrapper"/>
            <xs:element minOccurs="1" name="command"/>
            <xs:element minOccurs="0" name="params" type="paramsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="paramsType">
        <xs:sequence>
            <xs:element minOccurs="0" name="param" type="paramsItemType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="paramsItemType">
        <xs:sequence>
            <xs:element minOccurs="0" name="name" type="xs:string"/>
            <xs:element minOccurs="1" name="type" type="paramType"/>
            <xs:element minOccurs="0" name="required" type="xs:boolean"/>
            <xs:element minOccurs="0" name="config_path" type="xs:string"/>
            <xs:element minOccurs="0" name="output_format" type="xs:string"/>
        </xs:sequence>
        <xs:attributeGroup ref="paramsItemAttributeGroup"/>
    </xs:complexType>

    <xs:attributeGroup name="paramsItemAttributeGroup">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:attributeGroup>


    <xs:simpleType name="paramType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="cli"/>
            <xs:enumeration value="config"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== a42ss/flex-cli/src/lcli/config/samples/prototypes/commands.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="commands.xsd">
    <commands>
        <command id="gitw">
            <type>wrapper</type>
            <description>Git vcs management - wrapped commands</description>
            <args>
                <wrapper>base_wrapper</wrapper>
                <command>git</command>
            </args>
            <commands>
                <command id="save">
                    <type>cli</type>
                    <description>Save current state</description>
                    <args>
                        <command>
                            <![CDATA[git commit -am "${autocommit_message}" && git push origin]]>
                        </command>
                        <params>
                            <param id="author">
                                <type>cli</type>
                                <required>true</required>
                                <config_path>author</config_path>
                                <output_format>[<![CDATA["--$name=\"$value\"]]></output_format>
                            </param>
                        </params>
                    </args>
                </command>
            </commands>
        </command>
    </commands>
</config>
